### ISSUE TITLE
119.18.0.101` in `main.tf`???

### ISSUE THREAD

**Issue by seomago** [diegopacheco/terraform-docker#1]
Why should I set up s3 endpoint to `119.18.0.101` in `main.tf` [line 9]?
What is this IP address??
Thank you

**Comment by ejrgilbert** [comment]
That's the S3 endpoint that winds up getting set up by localstack. You can see that he created a virtual network in docker in the terraform-docker.sh script. Then when you run localstack, the S3 endpoint is accessible at either `localhost` (since he exposes that port) or at the above IP within the docker network.

Since the TF is run inside a docker container in the network, it's able to use the IP. Hopefully that makes sense. 

`localstack` actually runs in a docker container by default if you install the CLI and run `localstack start`. So if you want to just install localstack and terraform, you could get set up pretty easily. The code here is more complicated than necessary if you're open to installing the CLI tools instead of running everything through docker containers. I refactored in my fork if you want to look.
